### ISSUE TITLE
Best Use

### ISSUE THREAD

**Issue by nrurval** [mad-eye/pince#11]
I had a few questions.
1. Should I be declaring a seperate logger for each file or should I create just a few major ones?
2. Should I declare the loggers and level sets in the files they pertain to, or should I create a javascript file and declare them all there globally?

**Comment by jagill** [comment]
I tend to create a separate logger for each file or logical unit, and I declare them close to where they are used.  For example, if I have a `FooController`, a `BarController`, and a `DatabaseConnector`, each of those would be in their own separate files, and I'd declare a logger for each at the top of the file.  I also set the level when I declare them, but I often change the levels as I'm debugging (via the JS console, or env variables, etc).

Does this help?
