### ISSUE TITLE
where can see the logger record?

### ISSUE THREAD

**Issue by cffz0225** [mad-eye/pince#13]
hi ,so i deployed  meteor project on the server, where could see the logger content? that like "java log4j", some files?thank you.
others: the meteor server error hava the same output?

**Comment by wangfenjin** [comment]
Same question here.

How to log to file?

**Comment by intyro** [comment]
+1

**Comment by jagill** [comment]
Pince follows the 12-factor app paradigm, so all of it's output goes to stdout or stderr.  You can redirect the output to the file of your choice in the calling program.  A good reference for this is: http://tldp.org/HOWTO/Bash-Prog-Intro-HOWTO-3.html
