### ISSUE TITLE
Add support for colors on the browser console

### ISSUE THREAD

**Issue by gadicc** [mad-eye/pince#2]
As per http://stackoverflow.com/questions/7505623/colors-in-javascript-console

Would make reading logs a pleasure :)

**Comment by smeijer** [comment]
Will the `browserColors` branch ever being merged into `master`?

**Comment by jagill** [comment]
Just merged.  I will test it a bit this week and then release the packages.  Thanks for the bump!

**Comment by nrurval** [comment]
When will this feature be released ?

**Comment by jagill** [comment]
Thanks for the poke!  Just released.  Tell me if there are any issues.

**Comment by gadicc** [comment]
Just checked this out, it's awesome!  Thanks.  Will be forcing this version for updates of famous-views, so it will get pretty extensive testing and will let you know if there are any issues.

**Comment by jagill** [comment]
@gadicc Just pushed a fix in v0.0.9; you might want to use that instead!

**Comment by gadicc** [comment]
Copy that, @jagill!  Thanks for the heads up.
