### ISSUE TITLE
How do I direct log to file

### ISSUE THREAD

**Issue by adamgins** [mad-eye/pince#5]
HI, installed and all seems OK when direct to STDOUT running on my local server.

However, when I am running this on AWS Opsworks in their nodejs container, I need to specify a file location for the log file. 

Hoping you can help explain how I do that, pls?

**Comment by tkang007** [comment]
Hi,
With the default setting, server side log message display two timestamp.  I think first part might be displayed by Meteor itself, and the second timestamp might be provided by this library. 

Could you guide me how to solve this double timestamp case?  Many thanks in advance.

**Comment by jagill** [comment]
@adamgins Right now, pince is set up to follow the [12-factor app](http://12factor.net/logs), which states that all output should be to stdout or stderr; whatever environment manages the process is responsible for directing that to a file or other stream consumer.

I've never used Opswork, so I don't know if there's some good way to fit this into their framework.  I'd certainly consider a PR that made it compatible!

**Comment by jagill** [comment]
@tkang007 This would more properly be a separate issue.  However, you can run meteor with `meteor --raw-logs`, and it will not prepend its own timestamp.  Run `meteor help run` for more info.  Tell me if that's not working for you.
