### ISSUE TITLE
[Meteor] Respecting Meteor namespacing

### ISSUE THREAD

**Issue by splendido** [mad-eye/pince#6]
When using the package from inside another package the `Logger` global var is always visible, no matter whether you had `api.imply` within the `package.js` file or not.

``` javascript
Package.onUse(function(api) {
  api.use('jag:pince@0.0.5');
]
```

Should make the `Logger` variable available to the current package but not outside it. While

``` javascript
Package.onUse(function(api) {
  api.use('jag:pince@0.0.5');
  api.imply('jag:pince');
]
```

explicitely ask to make `Logger` available to whom is using the current package.

See the official docs for [use](https://docs.meteor.com/#/full/pack_use) and [imply](https://docs.meteor.com/#/full/pack_api_imply)

Tnx!

**Comment by jagill** [comment]
Sorry for taking so long on this.  I've been a bit busy; I'd be happy to look at a PR.  Otherwise I'll get to it soon-ish.

**Comment by jagill** [comment]
Sorry again for letting this languish.  I'm not realistically going to have time to do this, but I'm happy to take a PR for it.
