### ISSUE TITLE
[Meteor] Use official momentjs:moment

### ISSUE THREAD

**Issue by splendido** [mad-eye/pince#7]
In case this would not require to re-design the whole project, it would be great to bring in moment via its [official meteor package](https://atmospherejs.com/momentjs/moment) rather than via npm.

In principle this should prevent *loading* the moment code twice in case `momentjs:moment` is used for the application.

**Comment by jagill** [comment]
Fixed with 598cda083.

**Comment by splendido** [comment]
Awesome :+1: 

Tnx!
