### ISSUE TITLE
string format

### ISSUE THREAD

**Issue by eskan** [mad-eye/pince#8]
Hello,
is there a way to write something like this : 
log.info('found %d items' , 4);  
// found 4 items
regards,

**Comment by jagill** [comment]
Unfortunately, JavaScript doesn't have good printf support.  Supporting that well would be outside the scope of this library, but you could check out something like [underscore.string](http://epeli.github.io/underscore.string/#sprintf-string-format-arguments-gt-string) for a more general solution.
