### ISSUE TITLE
better use of browser console log levels

### ISSUE THREAD

**Issue by smeijer** [mad-eye/pince#9]
It seems to me that `pince` writes everything to `console.log`, while there are levels in addition to the basic `log` method. For example: `console.error`, `console.warn`, `console.info`, `console.debug`.

I'm aware of the fact that not every browser supports all these methods, but we could fall back to `log` if a specific method isn't available.

Supporting these levels, makes it easier to distinguish and filter individual log messages. Simply by using the browser console more efficiently.

**Comment by jagill** [comment]
One challenge is that `console.debug` in Node writes to stderr, which seems the opposite of what I want (I view stderr as a "serious" channel, while debug messages should not be serious).  I could use them only in the browser, but that seems a little weird.  Would you want `log.debug` to use `console.debug` in the browser, but `console.log` on the server?

**Comment by jagill** [comment]
Fixed in b9393275a134e821186db82607f7b0fdbdf09da2
